// <auto-generated />
namespace Section04_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OverrideDefaultConvention : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverrideDefaultConvention));
        
        string IMigrationMetadata.Id
        {
            get { return "201804261857411_OverrideDefaultConvention"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
